import type { Config } from "tailwindcss";

const color = (name: string) => `rgb(var(${name}) / <alpha-value>)`;

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        brand: {
          cream: color("--color-brand-cream"),
          peach: color("--color-brand-peach"),
          accent: color("--color-brand-accent"),
          "accent-hover": color("--color-brand-accent-hover"),
        },
        "primary-container": color("--color-primary-container"),
        "inverse-surface": color("--color-inverse-surface"),
        "on-error": color("--color-on-error"),
        "on-surface": color("--color-on-surface"),
        "surface-bright": color("--color-surface-bright"),
        "surface-container": color("--color-surface-container"),
        "primary-fixed": color("--color-primary-fixed"),
        "on-secondary-fixed-variant": color("--color-on-secondary-fixed-variant"),
        "secondary-container": color("--color-secondary-container"),
        background: color("--color-background"),
        "secondary-fixed-dim": color("--color-secondary-fixed-dim"),
        "on-primary": color("--color-on-primary"),
        "tertiary-fixed": color("--color-tertiary-fixed"),
        "on-background": color("--color-on-background"),
        "surface-container-low": color("--color-surface-container-low"),
        tertiary: color("--color-tertiary"),
        primary: color("--color-primary"),
        surface: color("--color-surface"),
        "inverse-on-surface": color("--color-inverse-on-surface"),
        "error-container": color("--color-error-container"),
        "on-tertiary-fixed": color("--color-on-tertiary-fixed"),
        "on-tertiary-container": color("--color-on-tertiary-container"),
        "on-secondary-fixed": color("--color-on-secondary-fixed"),
        "on-secondary-container": color("--color-on-secondary-container"),
        "on-secondary": color("--color-on-secondary"),
        "inverse-primary": color("--color-inverse-primary"),
        "on-error-container": color("--color-on-error-container"),
        "surface-variant": color("--color-surface-variant"),
        "surface-tint": color("--color-surface-tint"),
        "primary-fixed-dim": color("--color-primary-fixed-dim"),
        "surface-container-highest": color("--color-surface-container-highest"),
        outline: color("--color-outline"),
        "tertiary-fixed-dim": color("--color-tertiary-fixed-dim"),
        error: color("--color-error"),
        "on-primary-container": color("--color-on-primary-container"),
        "tertiary-container": color("--color-tertiary-container"),
        "on-primary-fixed": color("--color-on-primary-fixed"),
        "surface-container-lowest": color("--color-surface-container-lowest"),
        "on-tertiary": color("--color-on-tertiary"),
        "on-surface-variant": color("--color-on-surface-variant"),
        "secondary-fixed": color("--color-secondary-fixed"),
        "outline-variant": color("--color-outline-variant"),
        "on-tertiary-fixed-variant": color("--color-on-tertiary-fixed-variant"),
        "on-primary-fixed-variant": color("--color-on-primary-fixed-variant"),
        "surface-container-high": color("--color-surface-container-high"),
        secondary: color("--color-secondary"),
        "surface-dim": color("--color-surface-dim"),
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        unit: "4px",
        gutter: "12px",
        "card-padding": "20px",
        "tap-target-min": "48px",
      },
      fontFamily: {
        "body-md": ["var(--font-hind-siliguri)", "sans-serif"],
        "label-sm": ["var(--font-work-sans)", "sans-serif"],
        "headline-md": ["var(--font-hind-siliguri)", "sans-serif"],
        "label-lg": ["var(--font-work-sans)", "sans-serif"],
        "body-lg": ["var(--font-hind-siliguri)", "sans-serif"],
        "headline-lg": ["var(--font-hind-siliguri)", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
