import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        brand: {
          cream: "#fbf9f9",
          peach: "#efeded",
          accent: "#006565",
          "accent-hover": "#006a6a",
        },
        "primary-container": "#008080",
        "inverse-surface": "#303031",
        "on-error": "#ffffff",
        "on-surface": "#1b1c1c",
        "surface-bright": "#fbf9f9",
        "surface-container": "#efeded",
        "primary-fixed": "#93f2f2",
        "on-secondary-fixed-variant": "#802918",
        "secondary-container": "#fd876f",
        background: "#fbf9f9",
        "secondary-fixed-dim": "#ffb4a5",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#e4e4cc",
        "on-background": "#1b1c1c",
        "surface-container-low": "#f5f3f3",
        tertiary: "#5a5c49",
        primary: "#006565",
        surface: "#fbf9f9",
        "inverse-on-surface": "#f2f0f0",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#1b1d0e",
        "on-tertiary-container": "#fbfbe2",
        "on-secondary-fixed": "#3e0500",
        "on-secondary-container": "#732010",
        "on-secondary": "#ffffff",
        "inverse-primary": "#76d6d5",
        "on-error-container": "#93000a",
        "surface-variant": "#e4e2e2",
        "surface-tint": "#006a6a",
        "primary-fixed-dim": "#76d6d5",
        "surface-container-highest": "#e4e2e2",
        outline: "#6e7979",
        "tertiary-fixed-dim": "#c8c8b0",
        error: "#ba1a1a",
        "on-primary-container": "#e3fffe",
        "tertiary-container": "#737460",
        "on-primary-fixed": "#002020",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#3e4949",
        "secondary-fixed": "#ffdad3",
        "outline-variant": "#bdc9c8",
        "on-tertiary-fixed-variant": "#474836",
        "on-primary-fixed-variant": "#004f4f",
        "surface-container-high": "#e9e8e8",
        secondary: "#9f402d",
        "surface-dim": "#dbdada",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        unit: "4px",
        gutter: "12px",
        "card-padding": "20px",
        "tap-target-min": "48px",
      },
      fontFamily: {
        "body-md": ["var(--font-hind-siliguri)", "sans-serif"],
        "label-sm": ["var(--font-work-sans)", "sans-serif"],
        "headline-md": ["var(--font-hind-siliguri)", "sans-serif"],
        "label-lg": ["var(--font-work-sans)", "sans-serif"],
        "body-lg": ["var(--font-hind-siliguri)", "sans-serif"],
        "headline-lg": ["var(--font-hind-siliguri)", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
